CREATE TABLE "User" (
	"id" serial PRIMARY KEY NOT NULL,
	"first_name" varchar(255),
	"last_name" varchar(255),
	"email" varchar(255) NOT NULL,
	"phone_number" varchar(15),
	"password" varchar(255) NOT NULL,
	"company_name" varchar(255) NOT NULL,
	"is_verified" varchar DEFAULT 'false' NOT NULL,
	"is_active" varchar DEFAULT 'true' NOT NULL,
	"is_deleted" varchar DEFAULT 'false' NOT NULL,
	"is_blocked" varchar DEFAULT 'false' NOT NULL,
	"is_approved" varchar DEFAULT 'false' NOT NULL,
	"is_suspended" varchar DEFAULT 'false' NOT NULL,
	"is_password_reset" varchar DEFAULT 'false' NOT NULL,
	"is_email_verified" varchar DEFAULT 'false' NOT NULL,
	"is_phone_verified" varchar DEFAULT 'false' NOT NULL,
	"is_email_verified_at" timestamp,
	"is_phone_verified_at" timestamp,
	"is_password_reset_at" timestamp,
	"is_blocked_at" timestamp,
	"is_approved_at" timestamp,
	"is_suspended_at" timestamp,
	"is_deleted_at" timestamp,
	"is_active_at" timestamp,
	"is_verified_at" timestamp,
	"role" varchar DEFAULT 'user' NOT NULL,
	"refresh_token" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "User_email_unique" UNIQUE("email"),
	CONSTRAINT "User_phone_number_unique" UNIQUE("phone_number"),
	CONSTRAINT "User_refresh_token_unique" UNIQUE("refresh_token")
);
